# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue-green
  template:
    metadata:
      labels:
        color: blue-green
    spec:
      containers:
        - name: blue-green
          image: mtinside/blue-green:blue
