# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
spec:
  selector:
    matchLabels:
      app: blue-green
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - name: blue-green
          image: mtinside/blue-green:green
          imagePullPolicy: Always
